### ISSUE TITLE
There's no text at all in the rendered book!

### ISSUE THREAD

**Issue by zackw** [betrusted-io/xous-book#2]
- [X] I have checked the latest `main` branch to see if this has already been fixed
- [X] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:

All of them, but running example: https://betrusted.io/xous-book/foreword.html

Description of the problem:

This is what I see when I load https://betrusted.io/xous-book/foreword.html:

![Screenshot from 2022-02-09 09-35-01](https://user-images.githubusercontent.com/325899/153222783-3f752fab-a807-4643-b976-50a4afba4413.png)

As you can see, there is no text at all.

Looking at the page source, I do not see any actual text in the HTML, only a bunch of script tags.  I presume that these scripts are supposed to load and render the text, but they're not working for some reason.  There is no obvious indication of what went wrong in my browser's developer tools -- no failed HTTP requests, no JS errors.

Suggested fix:

Don't rely on JavaScript to render the text of each page.  Send down actual HTML from the server, as it was done in the old days.

**Comment by zackw** [comment]
... I did not look hard enough through the chapters -- what's really going on here is that most of the text hasn't been written yet.  https://betrusted.io/xous-book/ch03-01-memory-layout.html for example is displayed fine for me, and the actual text _is_ sent down as HTML from the server.  I apologize for jumping to conclusions.

I'm going to leave this open but please consider it a request to write _something_ in the first page that gets displayed when you load https://betrusted.io/xous-book/, even if it's just "this book is still being written please be patient".  So it is clear that this is not a technical glitch.

**Comment by bunnie** [comment]
Some comments have been added on the first few pages to try and indicate that the book is a work in progress. 

I think the general problem is that the Xous Book is where "finished" ideas go, and the Wiki is where the work in progress goes. Most everything is a work in progress so things mostly live on [the wiki](https://github.com/betrusted-io/betrusted-wiki/wiki) for now.

There's also some fuzziness still as to what point do things become not Xous and become Precursor specific. For example, probably USB update scripts don't belong here, and maybe even the filesystem layout doesn't even belong because it's not actually integral to the kernel itself. 

Sorry for the confusion.

**Comment by bunnie** [comment]
should be better now. closing the issue.
